// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonbSeh60yK0SJI6Cyo5gD9k02DAwMB5A',
    appId: '1:1085919889756:web:490fbf56563a1cf546d999',
    messagingSenderId: '1085919889756',
    projectId: 'social-app-85e3e',
    authDomain: 'social-app-85e3e.firebaseapp.com',
    storageBucket: 'social-app-85e3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC6iUsZKysoYjIWhJUkc-7CQYtxioH26I',
    appId: '1:1085919889756:android:afacc99967dbdc2646d999',
    messagingSenderId: '1085919889756',
    projectId: 'social-app-85e3e',
    storageBucket: 'social-app-85e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUA-sRWG0jbzlHh9mKkuTrokFRz4u-tI',
    appId: '1:1085919889756:ios:e1198019cb8bebfd46d999',
    messagingSenderId: '1085919889756',
    projectId: 'social-app-85e3e',
    storageBucket: 'social-app-85e3e.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );
}
